version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto
    command: ["--help"]  # Default to showing help, override with your command

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"

volumes:
  postgres_data:
